<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FinancialRecord;
use App\Models\Office;
use App\Models\User;

class FinancialRecordsSeeder extends Seeder
{
    public function run()
    {
        // Get first office and user for testing
        $office = Office::first();
        $user = User::first();
        
        if (!$office || !$user) {
            $this->command->warn('No office or user found. Please run OfficesSeeder and UsersSeeder first.');
            return;
        }

        $sampleRecords = [
            [
                'type' => 'DV',
                'description' => 'Payment for office supplies and equipment procurement',
                'supplier' => 'ABC Office Supplies Corp.',
                'pr_number' => 'PR-2026-001',
                'pr_amount' => 15000.00,
                'po_number' => 'PO-2026-001',
                'po_amount' => 14850.00,
                'obr_number' => 'OBR-2026-001',
                'voucher_number' => 'VCH-2026-001',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Document preparation',
                'remarks' => 'Initial procurement for Q1 2026',
            ],
            [
                'type' => 'INSPEC',
                'description' => 'Inspection fees for building renovation project',
                'supplier' => 'Quality Inspection Services Inc.',
                'pr_number' => 'PR-2026-002',
                'pr_amount' => 8500.00,
                'po_number' => 'PO-2026-002',
                'po_amount' => 8200.00,
                'obr_number' => 'OBR-2026-002',
                'voucher_number' => 'VCH-2026-002',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Inspection scheduled',
                'remarks' => 'Building renovation phase 1',
            ],
            [
                'type' => 'OBR',
                'description' => 'Obligation for vehicle maintenance and fuel expenses',
                'supplier' => 'AutoCare Maintenance Center',
                'pr_number' => 'PR-2026-003',
                'pr_amount' => 12000.00,
                'po_number' => 'PO-2026-003',
                'po_amount' => 11800.00,
                'obr_number' => 'OBR-2026-003',
                'voucher_number' => 'VCH-2026-003',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'FINISHED',
                'progress' => 'Completed',
                'remarks' => 'Q4 2025 vehicle maintenance completed',
            ],
            [
                'type' => 'OPG',
                'description' => 'Operational grant for community outreach program',
                'supplier' => 'Community Development Foundation',
                'pr_number' => 'PR-2026-004',
                'pr_amount' => 50000.00,
                'po_number' => 'PO-2026-004',
                'po_amount' => 50000.00,
                'obr_number' => 'OBR-2026-004',
                'voucher_number' => 'VCH-2026-004',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Fund disbursement in progress',
                'remarks' => 'Community outreach Q1 2026',
            ],
            [
                'type' => 'PR',
                'description' => 'Purchase request for new computer equipment',
                'supplier' => 'TechPro Solutions Ltd.',
                'pr_number' => 'PR-2026-005',
                'pr_amount' => 75000.00,
                'po_number' => 'PO-2026-005',
                'po_amount' => 73500.00,
                'obr_number' => 'OBR-2026-005',
                'voucher_number' => 'VCH-2026-005',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'CANCELLED',
                'progress' => 'Cancelled - budget reallocated',
                'remarks' => 'Cancelled due to budget constraints',
            ],
            [
                'type' => 'DV',
                'description' => 'Travel expenses for training seminar attendance',
                'supplier' => 'Travel & Tours Co.',
                'pr_number' => 'PR-2026-006',
                'pr_amount' => 8500.00,
                'po_number' => 'PO-2026-006',
                'po_amount' => 8200.00,
                'obr_number' => 'OBR-2026-006',
                'voucher_number' => 'VCH-2026-006',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Travel arrangements confirmed',
                'remarks' => 'Training seminar - Manila',
            ],
            [
                'type' => 'INSPEC',
                'description' => 'Quality inspection for newly delivered equipment',
                'supplier' => 'Certified Inspection Agency',
                'pr_number' => 'PR-2026-007',
                'pr_amount' => 4500.00,
                'po_number' => 'PO-2026-007',
                'po_amount' => 4300.00,
                'obr_number' => 'OBR-2026-007',
                'voucher_number' => 'VCH-2026-007',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'FINISHED',
                'progress' => 'Inspection completed - passed',
                'remarks' => 'Equipment quality verified',
            ],
            [
                'type' => 'OBR',
                'description' => 'Obligation for utility bills and office rent',
                'supplier' => 'Property Management Services',
                'pr_number' => 'PR-2026-008',
                'pr_amount' => 25000.00,
                'po_number' => 'PO-2026-008',
                'po_amount' => 25000.00,
                'obr_number' => 'OBR-2026-008',
                'voucher_number' => 'VCH-2026-008',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Monthly payment processing',
                'remarks' => 'January 2026 utilities and rent',
            ],
            // NEW ADDITIONAL RECORDS
            [
                'type' => 'DV',
                'description' => 'Payment for software licenses and subscriptions',
                'supplier' => 'Software Solutions Inc.',
                'pr_number' => 'PR-2026-009',
                'pr_amount' => 35000.00,
                'po_number' => 'PO-2026-009',
                'po_amount' => 34200.00,
                'obr_number' => 'OBR-2026-009',
                'voucher_number' => 'VCH-2026-009',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'License renewal processing',
                'remarks' => 'Annual software licenses for 2026',
            ],
            [
                'type' => 'PR',
                'description' => 'Purchase request for office furniture and fixtures',
                'supplier' => 'Modern Office Furniture Co.',
                'pr_number' => 'PR-2026-010',
                'pr_amount' => 45000.00,
                'po_number' => 'PO-2026-010',
                'po_amount' => 43800.00,
                'obr_number' => 'OBR-2026-010',
                'voucher_number' => 'VCH-2026-010',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Supplier selection in progress',
                'remarks' => 'New office setup - Department B',
            ],
            [
                'type' => 'OBR',
                'description' => 'Obligation for security services and equipment',
                'supplier' => 'SecureGuard Services Ltd.',
                'pr_number' => 'PR-2026-011',
                'pr_amount' => 18000.00,
                'po_number' => 'PO-2026-011',
                'po_amount' => 17600.00,
                'obr_number' => 'OBR-2026-011',
                'voucher_number' => 'VCH-2026-011',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'FINISHED',
                'progress' => 'Contract completed',
                'remarks' => 'Annual security services contract',
            ],
            [
                'type' => 'INSPEC',
                'description' => 'Safety inspection for electrical systems upgrade',
                'supplier' => 'Electrical Safety Inspectors',
                'pr_number' => 'PR-2026-012',
                'pr_amount' => 6500.00,
                'po_number' => 'PO-2026-012',
                'po_amount' => 6300.00,
                'obr_number' => 'OBR-2026-012',
                'voucher_number' => 'VCH-2026-012',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Inspection report pending',
                'remarks' => 'Electrical systems safety compliance',
            ],
            [
                'type' => 'OPG',
                'description' => 'Operational grant for research and development',
                'supplier' => 'Innovation Research Institute',
                'pr_number' => 'PR-2026-013',
                'pr_amount' => 85000.00,
                'po_number' => 'PO-2026-013',
                'po_amount' => 85000.00,
                'obr_number' => 'OBR-2026-013',
                'voucher_number' => 'VCH-2026-013',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Research phase 2',
                'remarks' => 'Q2 2026 R&D funding',
            ],
            [
                'type' => 'DV',
                'description' => 'Payment for consulting services',
                'supplier' => 'Business Consulting Partners',
                'pr_number' => 'PR-2026-014',
                'pr_amount' => 28000.00,
                'po_number' => 'PO-2026-014',
                'po_amount' => 27400.00,
                'obr_number' => 'OBR-2026-014',
                'voucher_number' => 'VCH-2026-014',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'ACTIVE',
                'progress' => 'Consulting services delivered',
                'remarks' => 'Strategic planning consultation',
            ],
            [
                'type' => 'PR',
                'description' => 'Purchase request for communication equipment',
                'supplier' => 'Telecom Solutions PH',
                'pr_number' => 'PR-2026-015',
                'pr_amount' => 32000.00,
                'po_number' => 'PO-2026-015',
                'po_amount' => 31200.00,
                'obr_number' => 'OBR-2026-015',
                'voucher_number' => 'VCH-2026-015',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'CANCELLED',
                'progress' => 'Cancelled - technical requirements changed',
                'remarks' => 'Equipment specifications updated',
            ],
            [
                'type' => 'OBR',
                'description' => 'Obligation for marketing and promotional materials',
                'supplier' => 'Creative Marketing Agency',
                'pr_number' => 'PR-2026-016',
                'pr_amount' => 15000.00,
                'po_number' => 'PO-2026-016',
                'po_amount' => 14700.00,
                'obr_number' => 'OBR-2026-016',
                'voucher_number' => 'VCH-2026-016',
                'office_origin' => $office->id,
                'current_office' => $office->id,
                'current_holder' => $user->id,
                'created_by' => $user->id,
                'status' => 'FINISHED',
                'progress' => 'Campaign completed',
                'remarks' => 'Q1 2026 marketing campaign',
            ],
        ];

        foreach ($sampleRecords as $record) {
            FinancialRecord::create($record);
        }

        $this->command->info('Sample financial records created successfully!');
    }
}
