<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestoreTodoDataSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing todos
        DB::table('todos')->delete();
        
        // Insert the todo data
        $todos = [
            [
                'id' => 1,
                'title' => '2025 COMMITMENTS AND PAYABLES',
                'description' => 'Incoming/Outgoing documents to finish all pending transactions',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'ADMIN UNIT',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'top',
                'status' => 'on-going',
            ],
            [
                'id' => 2,
                'title' => 'PDPFP',
                'description' => 'Input and review',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'done',
            ],
            [
                'id' => 3,
                'title' => 'JPA - LUECO',
                'description' => 'Prepare requirements for JPA',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'on-going',
            ],
            [
                'id' => 4,
                'title' => 'TECHNICAL - MEMO FOR APM',
                'description' => 'Prepare memo',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 5,
                'title' => 'ADMIN UNIT TRAINING - ASSESSMENT',
                'description' => 'Prepare assessment/justification',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'pending',
            ],
            [
                'id' => 6,
                'title' => 'TECHNICAL - 2026 ICT CONSO',
                'description' => 'Check consolidation',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'on-going',
            ],
            [
                'id' => 7,
                'title' => 'UNDELIVERED ICT SUPPLIES 2025',
                'description' => 'Consolidate and follow up supplier deliveries',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'MARGIE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'on-going',
            ],
            [
                'id' => 8,
                'title' => 'PREPARATION 2026 PURCHASE REQUESTS',
                'description' => 'Prepare 2026 PRs',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'MARGIE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'on-going',
            ],
            [
                'id' => 9,
                'title' => 'CONDEMNATION OF OLD AIRCON',
                'description' => 'Prepare request letter',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'MARGIE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'pending',
            ],
            [
                'id' => 10,
                'title' => 'FOLLOW UP UNDELIVERED ITEMS',
                'description' => 'Follow up Maam Rose on undelivered POs',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-02',
                'user_id' => 1,
                'assigned_to' => 'MELETH',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'on-going',
            ],
            [
                'id' => 29,
                'title' => 'GLOBE ECWT UPDATE',
                'description' => 'Update ECWT entries',
                'due_date' => null,
                'remarks' => 'Done updating but still same as Feb 24',
                'date_added' => '2026-02-20',
                'user_id' => 1,
                'assigned_to' => 'MELETH',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 30,
                'title' => 'CONVERGE PRODUCT PRESENTATION',
                'description' => 'Prepare documents for quotation',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-23',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'low',
                'status' => 'pending',
            ],
            [
                'id' => 31,
                'title' => 'PREPARATION OF TRIP TICKET',
                'description' => 'Prepare trip tickets Jan-Feb',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-23',
                'user_id' => 1,
                'assigned_to' => 'PATRICK',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 32,
                'title' => 'REVISION OF REQUEST FOR OVERTIME',
                'description' => 'Revise LUFA overtime request',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-24',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'done',
            ],
            [
                'id' => 33,
                'title' => 'PR - DATA PRIVACY TRAINING',
                'description' => 'Prepare PR',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-24',
                'user_id' => 1,
                'assigned_to' => 'MARGIE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'on-going',
            ],
            [
                'id' => 34,
                'title' => 'LUELCO - RESTORATION OF POWER FOR RELAY TOWERS',
                'description' => 'Coordinate restoration of power',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-24',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 35,
                'title' => 'LUELCO - ELECTRICITY BILLS REBATE',
                'description' => 'Prepare rebate request letter',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-24',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'on-going',
            ],
            [
                'id' => 36,
                'title' => 'PICTO MONTHLY OFFICE MEETING',
                'description' => 'February office meeting',
                'due_date' => '2026-02-25',
                'remarks' => null,
                'date_added' => '2026-02-24',
                'user_id' => 1,
                'assigned_to' => 'ADMIN UNIT',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'done',
            ],
            [
                'id' => 37,
                'title' => 'PBO CONCERN - Office Supplies and Computer Supplies',
                'description' => 'Office supplies budget issue',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-24',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'on-going',
            ],
            [
                'id' => 38,
                'title' => 'MAO - Calendar of Activities - 2026 ',
                'description' => 'Input calendar activities',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-24',
                'user_id' => 1,
                'assigned_to' => 'MARGIE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'low',
                'status' => 'pending',
            ],
            [
                'id' => 39,
                'title' => 'REQUEST FOR VAN - GOVEXCELLENCE',
                'description' => 'Request vehicle for March 4-6',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-25',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 40,
                'title' => 'Conduct of Baseline Assessment of Internal Control System Audit',
                'description' => 'Coordinate audit requirements',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-02-25',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 41,
                'title' => 'Conduct of Baseline Assessment of Internal Control System Audit',
                'description' => 'Fill up questionnaire',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-20',
                'user_id' => 1,
                'assigned_to' => 'ADMIN UNIT',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'on-going',
            ],
            [
                'id' => 42,
                'title' => 'Get certificate of apperance from GovXcellence',
                'description' => 'Request certificate',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-10',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'on-going',
            ],
            [
                'id' => 43,
                'title' => 'Accomplishment report for GovXcellence',
                'description' => 'Finalize report',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-10',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 44,
                'title' => 'Notice of Special Administrative Meeting ',
                'description' => 'As stated',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'top',
                'status' => 'done',
            ],
            [
                'id' => 45,
                'title' => 'Prepare PDC for Data Privacy Training at LMC2026',
                'description' => 'Prepare PDC for training',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => 'CLYDE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'pending',
            ],
            [
                'id' => 46,
                'title' => 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for Payment of Government Contracts',
                'description' => 'Submission deadline',
                'due_date' => '2026-03-31',
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => 'MARGIE',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => 'high',
                'status' => 'on-going',
            ],
            [
                'id' => 47,
                'title' => 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for Payment of Government Contracts',
                'description' => 'PICTO-OTH-MEMO-2026-0005.pdf',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'medium',
                'status' => 'cancelled',
            ],
            [
                'id' => 48,
                'title' => 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for Payment of Government Contracts',
                'description' => 'PICTO-OTH-MEMO-2026-0005.pdf',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'medium',
                'status' => 'cancelled',
            ],
            [
                'id' => 49,
                'title' => 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for Payment of Government Contracts',
                'description' => 'PICTO-OTH-MEMO-2026-0005.pdf',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'medium',
                'status' => 'cancelled',
            ],
            [
                'id' => 50,
                'title' => 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for Payment of Government Contracts',
                'description' => 'PICTO-OTH-MEMO-2026-0005.pdf',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'medium',
                'status' => 'cancelled',
            ],
            [
                'id' => 66,
                'title' => 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for Payment of Government Contracts',
                'description' => 'PICTO-OTH-MEMO-2026-0005.pdf',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'medium',
                'status' => 'cancelled',
            ],
            [
                'id' => 67,
                'title' => 'Attendance to the Sector-Based Strategy Re-Calibration',
                'description' => 'PICTO Schedule March 18, 2026 1:00-5:00 pm at Room 4 Speaker Pro-Tempore Francisco I. Ortega legislative Bdlg Provincial Capitol CSF',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'medium',
                'status' => 'done',
            ],
            [
                'id' => 68,
                'title' => 'Arta Advisory No. 2026-007, S2026 Reiteration on the Deadline of Submission of Compliance Under RA 11032 or EODB-EGSD Act of 2018 and its IPP',
                'description' => 'bit.ly/ARTACompliances',
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => 'clyde',
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'low',
                'status' => 'cancelled',
            ],
            [
                'id' => 69,
                'title' => 'Wellness and Self Care Experience March 25 8am onwards OPG Annex - OPG Executive Room (Day 2 Womens Month Celebration)',
                'description' => null,
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'low',
                'status' => 'done',
            ],
            [
                'id' => 70,
                'title' => 'Inspire Lead and celebrate Women March 26 8am-12noon PDRRMO (Day 3 Womens Month Celebration)',
                'description' => null,
                'due_date' => null,
                'remarks' => null,
                'date_added' => '2026-03-12',
                'user_id' => 1,
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'priority' => null,
                'status' => 'low',
                'status' => 'done',
            ],
        ];

        DB::table('todos')->insert($todos);
        
        $this->command->info('Restored ' . count($todos) . ' todo records successfully.');
    }
}
