-- Restore todo data
INSERT INTO `todos` (`id`, `title`, `description`, `due_date`, `remarks`, `date_added`, `user_id`, `assigned_to`, `created_at`, `updated_at`, `priority`, `status`) VALUES
(1, '2025 COMMITMENTS AND PAYABLES', 'Incoming/Outgoing documents to finish all pending transactions', NULL, '2026-02-02', 1, 'ADMIN UNIT', NOW(), NOW(), 'top', 'on-going'),
(2, 'PDPFP', 'Input and review', NULL, NULL, '2026-02-02', 1, 'CLYDE', NOW(), NOW(), 'high', 'done'),
(3, 'JPA - LUECO', 'Prepare requirements for JPA', NULL, '2026-02-02', 1, 'CLYDE', NOW(), NOW(), 'high', 'on-going'),
(4, 'TECHNICAL - MEMO FOR APM', 'Prepare memo', NULL, NULL, '2026-02-02', 1, 'CLYDE', NOW(), NOW(), 'medium', 'done'),
(5, 'ADMIN UNIT TRAINING - ASSESSMENT', 'Prepare assessment/justification', NULL, NULL, '2026-02-02', 1, 'CLYDE', NOW(), NOW(), 'high', 'pending'),
(6, 'TECHNICAL - 2026 ICT CONSO', 'Check consolidation', NULL, NULL, '2026-02-02', 1, 'CLYDE', NOW(), NOW(), 'medium', 'on-going'),
(7, 'UNDELIVERED ICT SUPPLIES 2025', 'Consolidate and follow up supplier deliveries', NULL, NULL, '2026-02-02', 1, 'MARGIE', NOW(), NOW(), 'medium', 'on-going'),
(8, 'PREPARATION 2026 PURCHASE REQUESTS', 'Prepare 2026 PRs', NULL, NULL, '2026-02-02', 1, 'MARGIE', NOW(), NOW(), 'high', 'on-going'),
(9, 'CONDEMNATION OF OLD AIRCON', 'Prepare request letter', NULL, NULL, '2026-02-02', 1, 'MARGIE', NOW(), NOW(), 'medium', 'pending'),
(10, 'FOLLOW UP UNDELIVERED ITEMS', 'Follow up Maam Rose on undelivered POs', NULL, 'Follow ups Feb 26, March 4, March 9-10', '2026-02-02', 1, 'MELETH', NOW(), NOW(), 'high', 'on-going'),
(29, 'GLOBE ECWT UPDATE', 'Update ECWT entries', NULL, 'Done updating but still same as Feb 24', '2026-02-20', 1, 'MELETH', NOW(), NOW(), 'medium', 'done'),
(30, 'CONVERGE PRODUCT PRESENTATION', 'Prepare documents for quotation', NULL, NULL, '2026-02-23', 1, 'CLYDE', NOW(), NOW(), 'low', 'pending'),
(31, 'PREPARATION OF TRIP TICKET', 'Prepare trip tickets Jan-Feb', NULL, 'Submitted to GSO March 10', '2026-02-23', 1, 'PATRICK', NOW(), NOW(), 'medium', 'done'),
(32, 'REVISION OF REQUEST FOR OVERTIME', 'Revise LUFA overtime request', NULL, NULL, '2026-02-24', 1, 'CLYDE', NOW(), NOW(), 'high', 'done'),
(33, 'PR -  DATA PRIVACY TRAINING', 'Prepare PR', NULL, NULL, '2026-02-24', 1, 'MARGIE', NOW(), NOW(), 'medium', 'on-going'),
(34, 'LUELCO - RESTORATION OF POWER FOR RELAY TOWERS', 'Coordinate restoration of power', NULL, 'Items delivered to LUELCO Aringay', '2026-02-24', 1, 'CLYDE', NOW(), NOW(), 'medium', 'done'),
(35, 'LUELCO - ELECTRICITY BILLS REBATE', 'Prepare rebate request letter', NULL, NULL, '2026-02-24', 1, 'CLYDE', NOW(), NOW(), 'medium', 'on-going'),
(36, 'PICTO MONTHLY OFFICE MEETING', 'February office meeting', '2026-02-25', NULL, '2026-02-24', 1, 'ADMIN UNIT', NOW(), NOW(), 'high', 'done'),
(37, 'PBO CONCERN - Office Supplies and Computer Supplies', 'Office supplies budget issue', NULL, 'Budget deficit noted', '2026-02-24', 1, 'CLYDE', NOW(), NOW(), 'high', 'on-going'),
(38, 'MAO - Calendar of Activities - 2026 ', 'Input calendar activities', NULL, NULL, '2026-02-24', 1, 'MARGIE', NOW(), NOW(), 'low', 'pending'),
(39, 'REQUEST FOR VAN - GOVEXCELLENCE', 'Request vehicle for March 4-6', NULL, 'No available vehicle, escalated to OPG', '2026-02-25', 1, 'CLYDE', MARGIE, NOW(), NOW(), 'medium', 'done'),
(40, 'Conduct of Baseline Assessment of Internal Control System Audit', 'Coordinate audit requirements', NULL, 'To follow ordinances', '2026-02-25', 1, 'CLYDE', MITCH, NOW(), NOW(), 'medium', 'done'),
(41, 'Conduct of Baseline Assessment of Internal Control System Audit', 'Fill up questionnaire', '2026-03-20', NULL, '2026-03-10', 1, 'ADMIN UNIT', NOW(), NOW(), 'medium', 'on-going'),
(42, 'Get certificate of apperance from GovXcellence', 'Request certificate', NULL, 'Messaged Sir Vicky', '2026-03-10', 1, 'CLYDE', NULL, NOW(), NOW(), 'high', 'on-going'),
(43, 'Accomplishment report for GovXcellence', 'Finalize report', NULL, 'For final edit', '2026-03-10', 1, 'CLYDE', NULL, NOW(), NOW(), 'medium', 'done'),
(44, 'Notice of Special Administrative Meeting ', 'As stated', '2026-03-12', NULL, '2026-03-12', 1, 'CLYDE', NULL, NOW(), NOW(), 'top', 'done'),
(45, 'Prepare PDC for Data Privacy Training at LMC2026', 'Prepare PDC for training', NULL, NULL, '2026-03-12', 1, 'CLYDE', NULL, NOW(), NOW(), 'high', 'pending'),
(46, 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for the Payment of Government Contracts', 'Submission deadline', '2026-03-31', NULL, '2026-03-12', 1, 'MARGIE', NULL, NOW(), NOW(), 'high', 'on-going'),
(47, 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for the Payment of Government Contracts', 'PICTO-OTH-MEMO-2026-0005.pdf', NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'medium', 'cancelled'),
(48, 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for the Payment of Government Contracts', 'PICTO-OTH-MEMO-2026-0005.pdf', NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'medium', 'cancelled'),
(49, 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for the Payment of Government Contracts', 'PICTO-OTH-MEMO-2026-0005.pdf', NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'medium', 'cancelled'),
(50, 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for the Payment of Government Contracts', 'PICTO-OTH-MEMO-2026-0005.pdf', NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'medium', 'cancelled'),
(66, 'Tax Clearance Certificate for Final Government Contracts(TCFG) as an additional Documentary requirement for the Payment of Government Contracts', 'PICTO-OTH-MEMO-2026-0005.pdf', NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'medium', 'cancelled'),
(67, 'Attendance to the Sector-Based Strategy Re-Calibration', 'PICTO Schedule March 18, 2026 1:00-5:00 pm at Room 4 Speaker Pro-Tempore Francisco I. Ortega legislative Bdlg Provincial Capitol CSF', NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'medium', 'done'),
(68, 'Arta Advisory No. 2026-007, S2026 Reiteration on the Deadline of Submission of Compliance Under RA 11032 or the EODB-EGSD Act of 2018 and its IPP', 'bit.ly/ARTACompliances', NULL, NULL, '2026-03-12', 1, 'clyde', NULL, NOW(), NOW(), 'low', 'cancelled'),
(69, 'Wellness and Self Care Experience March 25 8am onwards OPG Annex - OPG Executive Room (Day 2 Womens Month Celebration)', NULL, NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'low', 'done'),
(70, 'Inspire Lead and celebrate Women March 26 8am-12noon PDRRMO (Day 3 Womens Month Celebration)', NULL, NULL, NULL, '2026-03-12', 1, NULL, NULL, NOW(), NOW(), 'low', 'done');
