<?php

declare(strict_types=1);

$pdo = new PDO(
    'mysql:host=127.0.0.1;port=3306;dbname=pictorts;charset=utf8mb4',
    'root',
    'root',
    [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]
);

$officeMap = [];
$officeStmt = $pdo->query('SELECT id, code FROM offices');
foreach ($officeStmt as $office) {
    $officeMap[$office['code']] = (int) $office['id'];
}

$rows = [
    [
        'tracking_code' => 'PICTO-SO-2024-0001',
        'picto_number' => 'PICTO-SO-2024-0001',
        'date_received' => '2024-01-05',
        'originating_office_code' => 'PGSO',
        'memorandum_number' => null,
        'subject' => 'Designation as OIC of the PGSO',
        'particulars' => 'Engr. Robert L. Lelina, Assistant PGSO',
        'period' => 'January 8 to 12, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'ONGOING',
        'remarks' => 'received via AO GC c/o Sir Rhoman;',
        'received_via_online' => true,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0002',
        'picto_number' => 'PICTO-SO-2024-0002',
        'date_received' => '2024-01-08',
        'originating_office_code' => 'PGSO',
        'memorandum_number' => 'Memo 05-2024',
        'subject' => 'Designation as OIC of the PGSO',
        'particulars' => 'Mr. Francis Michael C. Eslava',
        'period' => 'January 8 to 12, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'revision to previous SO; received via AO GC c/o Sir Rhoman',
        'received_via_online' => true,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0003',
        'picto_number' => 'PICTO-SO-2024-0003',
        'date_received' => '2024-01-09',
        'originating_office_code' => 'PIO',
        'memorandum_number' => null,
        'subject' => 'Designation as OIC of the PIO',
        'particulars' => 'Ms. Camille R. Bumatay',
        'period' => 'January 12, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => null,
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0004',
        'picto_number' => 'PICTO-SO-2024-0004',
        'date_received' => '2024-01-09',
        'originating_office_code' => 'OPG',
        'memorandum_number' => null,
        'subject' => 'Designation as In-Charge of hte La Union Provincial Tourism Office',
        'particulars' => 'Mr. Julius Manabat, SAO',
        'period' => 'Effective Jan. 3, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0005',
        'picto_number' => 'PICTO-SO-2024-0005',
        'date_received' => '2024-01-10',
        'originating_office_code' => 'OPG',
        'memorandum_number' => null,
        'subject' => 'Extension of Designation as OIC-Provincial Government Assistant Department Head',
        'particulars' => 'Ms. Leony Gagni, Agricultural Center Chief II',
        'period' => 'until January 31, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => null,
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0006',
        'picto_number' => 'PICTO-SO-2024-0006',
        'date_received' => '2024-01-11',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO. No 11 S2024',
        'subject' => 'Management Assignments and Designation',
        'particulars' => 'Mr. Francisco Emmanuel R. Ortega III',
        'period' => 'Immediately',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0007',
        'picto_number' => 'PICTO-SO-2024-0007',
        'date_received' => '2024-01-15',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 12 S 2024',
        'subject' => 'Reassigned to the Office of the Provincial Administrator and Designation as Acting Assistant Provincial Administrator',
        'particulars' => 'Engr. Robert L. Lelina',
        'period' => null,
        'action_required' => null,
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0007A',
        'picto_number' => 'PICTO-SO-2024-0007A',
        'date_received' => '2024-01-15',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 12',
        'subject' => 'Designation as Acting Assistant Provincial Administrator',
        'particulars' => 'Engr. Robert L. Lelina',
        'period' => 'January 8, 2024 - January 7, 2025',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'via EMail',
        'received_via_online' => true,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0007B',
        'picto_number' => 'PICTO-SO-2024-0007B',
        'date_received' => '2024-01-16',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 15',
        'subject' => 'Designation as New ISO Facilitator/EHSMR and Other Management Assignments',
        'particulars' => 'Engr. Robert L. Lelina',
        'period' => 'Immediately',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'For initial of all ICTU Family',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0008',
        'picto_number' => 'PICTO-SO-2024-0008',
        'date_received' => '2024-01-17',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO N0.17',
        'subject' => 'Signing and approving authority- Rhoniel Dimaculangan',
        'particulars' => 'For application for Leave of Asst. Dept Head and rank-and-file employees, CTO, OJT/Immersion Form',
        'period' => 'Immediately',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0009',
        'picto_number' => 'PICTO-SO-2024-0009',
        'date_received' => '2024-01-24',
        'originating_office_code' => 'OPG',
        'memorandum_number' => null,
        'subject' => 'Designation as officer-in-charge of the PHO',
        'particulars' => 'Dr. Dan william Y. Dacanay, PHO I',
        'period' => 'Immediately',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'For our refence in our communication. Let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0010',
        'picto_number' => 'PICTO-SO-2024-0010',
        'date_received' => '2024-02-05',
        'originating_office_code' => 'OPG',
        'memorandum_number' => null,
        'subject' => 'Designation as Acting Governor',
        'particulars' => 'travel abroad for a personal trip to Japan',
        'period' => 'February 6 to 11, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team let them affix their initials',
        'received_via_online' => true,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0011',
        'picto_number' => 'PICTO-SO-2024-0011',
        'date_received' => '2024-02-07',
        'originating_office_code' => 'PGENRO',
        'memorandum_number' => 'Memo 2-2024',
        'subject' => 'Designation as In-Charge of Office',
        'particulars' => 'Jean Rose E. Go',
        'period' => 'February 7 to 8, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0012',
        'picto_number' => 'PICTO-SO-2024-0012',
        'date_received' => '2024-02-20',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 24',
        'subject' => 'Designation as officer-in-charge of Caba District Hospital (CDH)',
        'particulars' => 'Dr. Antonio Valdriz Jr',
        'period' => 'January 30 to February 12, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => null,
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0013',
        'picto_number' => 'PICTO-SO-2024-0013',
        'date_received' => '2024-02-20',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 23',
        'subject' => 'Designation as OIC-Provincial Government Assistant Department HEAD',
        'particulars' => 'Mr. MArcelo J. Otanes',
        'period' => 'February 12 to April 30, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0014',
        'picto_number' => 'PICTO-SO-2024-0014',
        'date_received' => '2024-02-26',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 26',
        'subject' => 'Designation as Full Disclosure Policy Focal Person',
        'particulars' => 'MA. Ashley Ebreo, Ma. Angelica de Guzman',
        'period' => 'take effect immediately',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'Ash/Ange please note on your indicated responsibilities. for you compliance',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0015',
        'picto_number' => 'PICTO-SO-2024-0015',
        'date_received' => '2024-02-28',
        'originating_office_code' => 'PPDO',
        'memorandum_number' => 'SO No. 5',
        'subject' => 'Designation as OIC',
        'particulars' => 'EnP Roshelle A. Mamaril',
        'period' => 'March 4, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team. let them affix their initials',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0016',
        'picto_number' => 'PICTO-SO-2024-0016',
        'date_received' => '2024-03-13',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 32',
        'subject' => 'Signing and Approving Authority - FRancisco Emmanuel "Pacoy" R. Ortega III',
        'particulars' => 'FRancisco Emmanuel "Pacoy" R. Ortega III for sign and approve TO of DH travelling outside La Union and Overtime Services of Departments',
        'period' => 'take effect immediately',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => null,
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0017',
        'picto_number' => 'PICTO-SO-2024-0017',
        'date_received' => '2024-03-13',
        'originating_office_code' => 'PTO',
        'memorandum_number' => 'Memo 05-2024',
        'subject' => 'Designation as Officer-in-Charge of PTO',
        'particulars' => 'Clarinda Vidamo',
        'period' => 'March 12 - 15, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0018',
        'picto_number' => 'PICTO-SO-2024-0018',
        'date_received' => '2024-03-25',
        'originating_office_code' => 'PEO',
        'memorandum_number' => 'Memo',
        'subject' => 'Designation as Officer-in-Charge of PEO',
        'particulars' => 'Engr. Emille F. Martinez',
        'period' => 'March 18 to 31, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0019',
        'picto_number' => 'PICTO-SO-2024-0019',
        'date_received' => '2024-04-03',
        'originating_office_code' => 'PGENRO',
        'memorandum_number' => 'SO 1',
        'subject' => 'Designation as Officer-in-charge',
        'particulars' => 'Raquel Orpilla, Supervising Env. Mgmnt Specialist',
        'period' => 'April 2-8, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0020',
        'picto_number' => 'PICTO-SO-2024-0020',
        'date_received' => '2024-04-22',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO 35',
        'subject' => 'Designation as office-in-charge of PHO',
        'particulars' => 'Gretchell . Carbonell, M.D',
        'period' => 'April 18 to May 3, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination to the team',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0021',
        'picto_number' => 'PICTO-SO-2024-0021',
        'date_received' => '2024-04-24',
        'originating_office_code' => 'LUPTO',
        'memorandum_number' => 'Office Order No. 1',
        'subject' => 'Designation as OIC in the LUPTO',
        'particulars' => "Hanzel D. Guerrero, Jr.\nSenior Tourism Operations Officer",
        'period' => 'April 25-29, 2024',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => null,
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0022',
        'picto_number' => 'PICTO-SO-2024-0022',
        'date_received' => '2024-05-02',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO NO. 40',
        'subject' => 'Extension of Designation as OIC-Assistant Provincial Budget Officer',
        'particulars' => 'MS. GENELEN B. NISPEROS, SAO',
        'period' => 'Extended until April 25, 2025',
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'PICTO-SO-2024-0023',
        'picto_number' => 'PICTO-SO-2024-0023',
        'date_received' => '2024-05-14',
        'originating_office_code' => 'OPG',
        'memorandum_number' => 'SO No. 43',
        'subject' => "Designation as Customer Feedback, Citizen's Charter, ISO and Department DCC",
        'particulars' => null,
        'period' => null,
        'action_required' => 'for dissemination',
        'endorsed_to' => 'ASS',
        'status' => 'COMPLETED',
        'remarks' => 'for dissemination',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
    [
        'tracking_code' => 'IMPORT-SO-2024-0024',
        'picto_number' => null,
        'date_received' => '2024-05-21',
        'originating_office_code' => 'PBO',
        'memorandum_number' => 'Memo No. 003 S 2024',
        'subject' => 'Designation as Officer-in-Charge of the PBO',
        'particulars' => 'Genelen B. Nisperos, SAO, OIC-APBO',
        'period' => 'May 22-23',
        'action_required' => null,
        'endorsed_to' => 'ASS',
        'status' => 'ONGOING',
        'remarks' => 'Dissemenate to the team',
        'received_via_online' => false,
        'shared_drive_link' => null,
    ],
];

$checkByPictoStmt = $pdo->prepare(
    'SELECT id FROM documents WHERE doc_number = ? OR picto_number = ? LIMIT 1'
);

$checkByFallbackStmt = $pdo->prepare(
    'SELECT id FROM documents WHERE date_received = ? AND subject = ? AND memorandum_number <=> ? LIMIT 1'
);

$insertStmt = $pdo->prepare(
    'INSERT INTO documents (
        dts_number,
        transaction_number,
        picto_number,
        doc_number,
        memorandum_number,
        period,
        particulars,
        document_type,
        direction,
        originating_office,
        to_office,
        current_office,
        current_holder,
        subject,
        action_required,
        endorsed_to,
        date_received,
        status,
        remarks,
        shared_drive_link,
        received_via_online,
        encoded_by,
        created_at,
        updated_at
    ) VALUES (
        :dts_number,
        :transaction_number,
        :picto_number,
        :doc_number,
        :memorandum_number,
        :period,
        :particulars,
        :document_type,
        :direction,
        :originating_office,
        :to_office,
        :current_office,
        :current_holder,
        :subject,
        :action_required,
        :endorsed_to,
        :date_received,
        :status,
        :remarks,
        :shared_drive_link,
        :received_via_online,
        :encoded_by,
        :created_at,
        :updated_at
    )'
);

$inserted = 0;
$skipped = 0;

$pdo->beginTransaction();

try {
    foreach ($rows as $row) {
        $officeCode = $row['originating_office_code'];

        if (! isset($officeMap[$officeCode])) {
            throw new RuntimeException("Missing office code in database: {$officeCode}");
        }

        $existingId = null;

        if ($row['picto_number'] !== null) {
            $checkByPictoStmt->execute([$row['picto_number'], $row['picto_number']]);
            $existingId = $checkByPictoStmt->fetchColumn() ?: null;
        } else {
            $checkByFallbackStmt->execute([
                $row['date_received'],
                $row['subject'],
                $row['memorandum_number'],
            ]);
            $existingId = $checkByFallbackStmt->fetchColumn() ?: null;
        }

        if ($existingId !== null) {
            $skipped++;
            echo "Skipped existing row: " . ($row['picto_number'] ?? $row['subject']) . PHP_EOL;
            continue;
        }

        $insertStmt->execute([
            'dts_number' => $row['tracking_code'],
            'transaction_number' => $row['picto_number'],
            'picto_number' => $row['picto_number'],
            'doc_number' => $row['picto_number'],
            'memorandum_number' => $row['memorandum_number'],
            'period' => $row['period'],
            'particulars' => $row['particulars'],
            'document_type' => 'SO',
            'direction' => 'INCOMING',
            'originating_office' => $officeMap[$officeCode],
            'to_office' => null,
            'current_office' => $officeMap['PICTO'] ?? null,
            'current_holder' => null,
            'subject' => $row['subject'],
            'action_required' => $row['action_required'],
            'endorsed_to' => $row['endorsed_to'],
            'date_received' => $row['date_received'],
            'status' => $row['status'],
            'remarks' => $row['remarks'],
            'shared_drive_link' => $row['shared_drive_link'],
            'received_via_online' => $row['received_via_online'] ? 1 : 0,
            'encoded_by' => null,
            'created_at' => $row['date_received'] . ' 00:00:00',
            'updated_at' => $row['date_received'] . ' 00:00:00',
        ]);

        $inserted++;
        echo "Inserted: " . ($row['picto_number'] ?? $row['subject']) . PHP_EOL;
    }

    $pdo->commit();

    echo PHP_EOL;
    echo "Import complete." . PHP_EOL;
    echo "Inserted: {$inserted}" . PHP_EOL;
    echo "Skipped: {$skipped}" . PHP_EOL;
} catch (Throwable $e) {
    $pdo->rollBack();
    fwrite(STDERR, 'Import failed: ' . $e->getMessage() . PHP_EOL);
    exit(1);
}
